### ISSUE TITLE
fix "Invalid padding string 'SAME'" error that pytorch > 1.7.1 raises 

### ISSUE THREAD

**Issue by NickleDave** [yardencsGitHub/tweetynet#166]
as pointed out by @zhehao-nkd (thank you!) in https://github.com/NickleDave/vak/issues/370
(full error copied and pasted below).

This is a bug in `tweetynet` not `vak`.
The PR should link this issue and the `vak` issue to close both.

A workaround is just to install earlier versions as described here:
https://github.com/NickleDave/vak/issues/370#issuecomment-892336619

Not sure yet what best fix is.
May be as simple as just changing the defaults to lowercase.

But we should handle this before publication.

https://github.com/NickleDave/vak/issues/370#issue-958977886

> I followed the manual to train the tweetynet model by running:
> 
>     vak train gy6or6_train.toml
> 
> But I got this error report:
> 
>     Traceback (most recent call last):
>     File "/home/chengzh/anaconda3/envs/vak-env/bin/vak", line 8, in
>     sys.exit(main())
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/main.py", line 45, in main
>     cli.cli(command=args.command, config_file=args.configfile)
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/cli/cli.py", line 30, in cli
>     COMMAND_FUNCTION_MAPcommand
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/cli/train.py", line 69, in train
>     logger=logger,
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/core/train.py", line 271, in train
>     logger=logger,
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/vak/models/models.py", line 72, in from_model_config_map
>     config=model_config, logger=logger
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/tweetynet/model.py", line 15, in from_config
>     network = TweetyNet(**config['network'])
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/tweetynet/network.py", line 139, in init
>     padding=padding
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/tweetynet/network.py", line 21, in init
>     super(Conv2dTF, self).init(*args, **kwargs)
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 432, in init
>     False, _pair(0), groups, bias, padding_mode, **factory_kwargs)
>     File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 92, in init
>     padding, valid_padding_strings))
>     ValueError: Invalid padding string 'SAME', should be one of {'valid', 'same'}
> 
> It seems that the torch need lowercase padding string now. How should I solve this problem, maybe by downgrading some packages?

**Comment by NickleDave** [comment]
Coming back to this, I now see where tensorflow-like "same" padding was added to `torch.nn.conv2d` back in March:
https://github.com/pytorch/pytorch/commit/04e0cbf5a9f073a1b73195537c12fb332c2fddd9#diff-db28bf59508ce2064dfd833cede78086de03b9567550a1a53f110256385ae7a0

Odds are we could just remove our homegrown `conv2d`-layer and use what is now in `torch`.

But I am paranoid that some low-level difference might subtly change our results, and I would like to maintain backwards compatibility.

The source of the error is that `padding` will be in `kwargs`, so it just gets passed blindly to the `torch.nn.Conv2d` class we are sub-classing, when we call `super`:  
```
File "/home/chengzh/anaconda3/envs/vak-env/lib/python3.6/site-packages/tweetynet/network.py", line 21, in init
super(Conv2dTF, self).init(*args, **kwargs)
```

So for now, to fix this, I am going to remove the `padding` keyword argument from `kwargs` and pass in everything else.
